language: python
dist: xenial
cache: pip
python:
    - "3.6"
    - "3.7"
    - "3.8-dev"
before_install:
    - wget https://github.com/f-prime/fist/archive/master.zip
    - mkdir fist-build
    - unzip master.zip -d fist-build
    - cd fist-build/fist-master
    - make
    - cd ../..
    - ./fist-build/fist-master/bin/fist &
install:
    - pip install -e .[codecov]
script:
    - python setup.py test
after_success:
    - codecov
